name: push-image

on:
  workflow_run:
    workflows: ["ci"]
    types: [completed]
    branches: ["main"]

env:
  AWS_REGION: us-west-2
  ECR_REPOSITORY: nl-api-flask

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  push-image:
    name: Push image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.vars.outputs.sha_short }}
          target: production

      - name: Checkout argocd config repo
        uses: actions/checkout@v4
        with:
          repository: NickLavrov/nl-api-argocd-config
          ref: preprod
          path: nl-api-argocd-config
          token: ${{secrets.PUSH_TOKEN}}

      - name: Update helm values
        working-directory: ./nl-api-argocd-config/apps/preprod
        run: |
          if [[ "$(git status --porcelain)" == "" ]]; then
            cat nl-api-flask.yaml
            sed -i 's/^\( *tag: \).*/\1${{ steps.vars.outputs.sha_short }}/' nl-api-flask.yaml
            echo "SED RAN"
            cat nl-api-flask.yaml
          fi

      - name: Commit new file
        working-directory: ./nl-api-argocd-config/apps/preprod
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "$USERNAME"
          git add nl-api-flask.yaml
          git commit -m "Update image tag"
          git push https://$USERNAME:$REPO_KEY@github.com/NickLavrov/nl-api-argocd-config.git
        env:
          REPO_KEY: ${{ secrets.PUSH_TOKEN }}
          USERNAME: github-actions[bot]

  on-failure:
    name: Print failure message
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
      - run: exit 1
